### ISSUE TITLE
Reality Check

### ISSUE THREAD

**Issue by bashify** [Sector443/eth_keyfun#1]
Do you even crypto? Any weak key you have found yet using this?

https://github.com/Sector443/eth_keyfun/blob/52ba4e350d704f3b04e91c0763b62d30eac1392c/eth_keyfun.py#L51

Just wrapping you name and a fancy product name around common sense is not called research.
btw I got this from [https://www.owaspseasides.com](https://www.owaspseasides.com)

**Comment by cougarbytes** [comment]
I never called it a research, this tool not for serious use

**Comment by cougarbytes** [comment]
have look at to my slides you will get idea about mindset behind this tool, I am not fool who will try to brute force all 115792089237316195423570985008687907853269984665640564039457584007913129639936 possible ethereum private keys [eth_keyfun.pptx](https://1drv.ms/p/s!Ag5D0P6imhKWnBM5pwwrQkfyIdhF)

**Comment by cougarbytes** [comment]
I will update the docs and will mention that this tool just for CTFs
